// Arayüz metinleri. Yeni bir anahtar eklerken iki dili de güncelleyin.
export const UI_STRINGS = {
  tr: {
    'app.title': 'Roman Uzay Teleskobu 3D',
    'app.heading': 'Nancy Grace Roman Uzay Teleskobu',
    'app.short': 'Roman Uzay Teleskobu',
    'app.subheading': 'İnteraktif 3D model · NASA',
    'app.description': "NASA'nın Nancy Grace Roman Uzay Teleskobu'nu tarayıcıda keşfedin: parçalarına ayırın, içini görün, ışık yolunu ve uzayda açılışını izleyin. Türkçe ve İngilizce interaktif 3D model.",

    'a11y.skipToParts': 'Parça listesine atla',
    'a11y.canvas': 'Roman Uzay Teleskobu interaktif 3D modeli',
    'a11y.canvasHelp': '3D sahne. Fareyle döndürebilir, yakınlaştırabilirsiniz. Parçaları klavyeyle keşfetmek için Parçalar listesini kullanın.',
    'a11y.tools': 'Araçlar',

    'loader.loading': '3D model hazırlanıyor…',
    'loader.retry': 'Tekrar dene',
    'loader.fileTitle': '<strong>Bu sayfa doğrudan dosyadan açılamaz.</strong>',
    'loader.fileBody': 'Tarayıcılar güvenlik nedeniyle JavaScript modüllerini <code>file://</code> adresinden yüklemez. Proje klasöründe bir yerel sunucu başlatın (örneğin <code>npx serve</code> veya <code>python3 -m http.server</code>) ya da canlı demoyu açın.',
    'loader.fileLink': 'Canlı demoyu aç',
    'error.webgl': 'Tarayıcınız ya da cihazınız WebGL desteklemiyor, bu yüzden 3D model gösterilemiyor. Güncel bir Chrome, Edge, Firefox veya Safari ile deneyin.',
    'error.load': '3D kütüphanesi yüklenemedi. İnternet bağlantınızı kontrol edip yeniden deneyin.',

    'top.language': 'Dil',
    'top.share': 'Bağlantıyı paylaş',
    'top.help': 'Yardım ve kısayollar',
    'top.fullscreen': 'Tam ekran',
    'top.settings': 'Ayarlar',

    'settings.quality': 'Görüntü kalitesi',
    'settings.auto': 'Otomatik',
    'settings.high': 'Yüksek',
    'settings.low': 'Düşük (pil dostu)',
    'settings.sun': "Güneş, Dünya ve Ay'ı göster",
    'settings.about': 'Hakkında ve kaynaklar',

    'tool.tour': 'Rehberli tur',
    'tool.parts': 'Parçalar',
    'tool.inside': 'İçini gör',
    'tool.light': 'Işık yolu',
    'tool.deploy': 'Uzayda açılış',
    'tool.dims': 'Boyutlar',
    'tool.labels': 'Etiketler',
    'tool.mission': 'Görev',
    'tool.fov': 'Görüş alanı',
    'tool.l2': 'L2 yörüngesi',

    'ctrl.explode': 'Parçalara ayır',
    'ctrl.reset': 'Görünümü sıfırla',
    'ctrl.autorotate': 'Otomatik döndür',
    'ctrl.screenshot': 'Ekran görüntüsü al',

    'player.close': 'Kapat',
    'player.prev': 'Önceki adım',
    'player.next': 'Sonraki adım',
    'player.play': 'Oynat',
    'player.pause': 'Duraklat',
    'player.count': '{n} / {total}',
    'player.tour': 'Rehberli tur',
    'player.light': 'Işık yolu',
    'player.deploy': 'Uzayda açılış',

    'parts.title': 'Parçalar',
    'parts.lead': 'Bir parça seçin: kamera ona döner ve ayrıntılar açılır.',
    'panel.close': 'Kapat',

    'group.optics': 'Teleskop ve optik',
    'group.instruments': 'Bilim aletleri',
    'group.spacecraft': 'Uzay aracı',

    'layer.outer': 'Dış yapı',
    'layer.inner': 'İç parça',
    'layer.orbit': 'Yörünge',
    'layer.mission': 'Görev',

    'info.highlights': 'Öne çıkanlar',
    'info.specs': 'Teknik değerler',
    'info.focus': 'Kameraya al',
    'info.inside': 'İçini gör',
    'info.light': 'Işık yolunu göster',
    'info.deploy': 'Açılışı izle',
    'info.prev': 'Önceki parça',
    'info.next': 'Sonraki parça',

    'hint.desktop': 'Sürükle: döndür · Tekerlek: yakınlaştır · Sağ tık: kaydır · Bir parçaya tıkla: ayrıntılar · <kbd>?</kbd> kısayollar',
    'hint.touch': 'Tek parmak: döndür · İki parmak: yakınlaştır ve kaydır · Parçaya dokun: ayrıntılar',

    'toast.linkCopied': 'Bağlantı panoya kopyalandı',
    'toast.screenshot': 'Ekran görüntüsü kaydedildi',
    'toast.offline': 'Model artık çevrimdışı da açılabilir',
    'toast.lowQuality': 'Akıcılık için görüntü kalitesi düşürüldü',

    'help.title': 'Nasıl kullanılır?',
    'help.mouse': 'Fare ve dokunmatik',
    'help.mouseRotate': 'Sol tuşla sürükle / tek parmak: döndür',
    'help.mouseZoom': 'Tekerlek / iki parmak: yakınlaştır',
    'help.mousePan': 'Sağ tuşla sürükle / iki parmakla kaydır: kaydır',
    'help.mouseClick': 'Parçaya tıkla / dokun: ayrıntıları aç',
    'help.mouseDouble': 'Boş alana çift tıkla: görünümü sıfırla',
    'help.keys': 'Klavye kısayolları',
    'help.keyTour': 'Rehberli turu başlat',
    'help.keyParts': 'Parça listesini aç',
    'help.keyInside': 'İçini gör',
    'help.keyLight': 'Işık yolu',
    'help.keyDeploy': 'Uzayda açılış',
    'help.keyExplode': 'Parçalara ayır / birleştir',
    'help.keyDims': 'Boyutlar',
    'help.keyLabels': 'Etiketleri göster / gizle',
    'help.keyCycle': 'Önceki / sonraki parça',
    'help.keyReset': 'Görünümü sıfırla',
    'help.keyRotate': 'Otomatik döndür',
    'help.keyFullscreen': 'Tam ekran',
    'help.keyEsc': 'Paneli ya da modu kapat',
    'help.keyHelp': 'Bu pencere',
    'help.about': 'Model, NASA\'nın kamuya açık görsel ve teknik bilgilerine dayanarak eğitim amacıyla hazırlanmış şematik bir modeldir; ölçüler yaklaşıktır.',

    'dims.length': 'Uzunluk ≈ {v} m',
    'dims.height': 'Yükseklik ≈ {v} m',
    'dims.width': 'Genişlik ≈ {v} m',
    'dims.mirror': 'Birincil ayna: 2,4 m',
    'dims.person': 'İnsan: 1,8 m',

    'scene.sun': 'Güneş',
    'scene.earth': 'Dünya',
    'scene.moon': 'Ay',
  },

  en: {
    'app.title': 'Roman Space Telescope 3D',
    'app.heading': 'Nancy Grace Roman Space Telescope',
    'app.short': 'Roman Space Telescope',
    'app.subheading': 'Interactive 3D model · NASA',
    'app.description': "Explore NASA's Nancy Grace Roman Space Telescope in your browser: take it apart, look inside, follow the light path and watch it unfold in space. Interactive 3D model in English and Turkish.",

    'a11y.skipToParts': 'Skip to the parts list',
    'a11y.canvas': 'Interactive 3D model of the Roman Space Telescope',
    'a11y.canvasHelp': '3D scene. Rotate and zoom with the mouse. Use the Parts list to explore the components with the keyboard.',
    'a11y.tools': 'Tools',

    'loader.loading': 'Preparing the 3D model…',
    'loader.retry': 'Try again',
    'loader.fileTitle': '<strong>This page can’t be opened directly from a file.</strong>',
    'loader.fileBody': 'For security reasons, browsers don’t load JavaScript modules from <code>file://</code> addresses. Start a local server in the project folder (for example <code>npx serve</code> or <code>python3 -m http.server</code>) or open the live demo.',
    'loader.fileLink': 'Open the live demo',
    'error.webgl': 'Your browser or device doesn’t support WebGL, so the 3D model can’t be displayed. Try an up-to-date version of Chrome, Edge, Firefox or Safari.',
    'error.load': 'The 3D library couldn’t be loaded. Check your internet connection and try again.',

    'top.language': 'Language',
    'top.share': 'Share link',
    'top.help': 'Help and shortcuts',
    'top.fullscreen': 'Full screen',
    'top.settings': 'Settings',

    'settings.quality': 'Graphics quality',
    'settings.auto': 'Automatic',
    'settings.high': 'High',
    'settings.low': 'Low (battery saver)',
    'settings.sun': 'Show the Sun, Earth and Moon',
    'settings.about': 'About and sources',

    'tool.tour': 'Guided tour',
    'tool.parts': 'Parts',
    'tool.inside': 'Look inside',
    'tool.light': 'Light path',
    'tool.deploy': 'Deployment',
    'tool.dims': 'Dimensions',
    'tool.labels': 'Labels',
    'tool.mission': 'Mission',
    'tool.fov': 'Field of view',
    'tool.l2': 'L2 orbit',

    'ctrl.explode': 'Exploded view',
    'ctrl.reset': 'Reset view',
    'ctrl.autorotate': 'Auto-rotate',
    'ctrl.screenshot': 'Take a screenshot',

    'player.close': 'Close',
    'player.prev': 'Previous step',
    'player.next': 'Next step',
    'player.play': 'Play',
    'player.pause': 'Pause',
    'player.count': '{n} / {total}',
    'player.tour': 'Guided tour',
    'player.light': 'Light path',
    'player.deploy': 'Deployment',

    'parts.title': 'Parts',
    'parts.lead': 'Pick a part: the camera turns to it and the details open.',
    'panel.close': 'Close',

    'group.optics': 'Telescope and optics',
    'group.instruments': 'Science instruments',
    'group.spacecraft': 'Spacecraft',

    'layer.outer': 'Exterior',
    'layer.inner': 'Interior component',
    'layer.orbit': 'Orbit',
    'layer.mission': 'Mission',

    'info.highlights': 'Key facts',
    'info.specs': 'Specifications',
    'info.focus': 'Focus camera',
    'info.inside': 'Look inside',
    'info.light': 'Show the light path',
    'info.deploy': 'Watch deployment',
    'info.prev': 'Previous part',
    'info.next': 'Next part',

    'hint.desktop': 'Drag: rotate · Scroll: zoom · Right-drag: pan · Click a part: details · <kbd>?</kbd> shortcuts',
    'hint.touch': 'One finger: rotate · Two fingers: zoom and pan · Tap a part: details',

    'toast.linkCopied': 'Link copied to the clipboard',
    'toast.screenshot': 'Screenshot saved',
    'toast.offline': 'The model now works offline too',
    'toast.lowQuality': 'Graphics quality lowered for smoother motion',

    'help.title': 'How to use',
    'help.mouse': 'Mouse and touch',
    'help.mouseRotate': 'Left-drag / one finger: rotate',
    'help.mouseZoom': 'Scroll wheel / pinch: zoom',
    'help.mousePan': 'Right-drag / two-finger drag: pan',
    'help.mouseClick': 'Click / tap a part: open its details',
    'help.mouseDouble': 'Double-click empty space: reset the view',
    'help.keys': 'Keyboard shortcuts',
    'help.keyTour': 'Start the guided tour',
    'help.keyParts': 'Open the parts list',
    'help.keyInside': 'Look inside',
    'help.keyLight': 'Light path',
    'help.keyDeploy': 'Deployment',
    'help.keyExplode': 'Explode / assemble',
    'help.keyDims': 'Dimensions',
    'help.keyLabels': 'Show / hide labels',
    'help.keyCycle': 'Previous / next part',
    'help.keyReset': 'Reset the view',
    'help.keyRotate': 'Auto-rotate',
    'help.keyFullscreen': 'Full screen',
    'help.keyEsc': 'Close the panel or mode',
    'help.keyHelp': 'This window',
    'help.about': 'This is a schematic educational model based on NASA’s public images and technical information; dimensions are approximate.',

    'dims.length': 'Length ≈ {v} m',
    'dims.height': 'Height ≈ {v} m',
    'dims.width': 'Width ≈ {v} m',
    'dims.mirror': 'Primary mirror: 2.4 m',
    'dims.person': 'Person: 1.8 m',

    'scene.sun': 'Sun',
    'scene.earth': 'Earth',
    'scene.moon': 'Moon',
  },
};
